/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/can1.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/can1.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, -0.054, 0]}>
        <mesh geometry={nodes.BezierCurve001.geometry} material={materials['can body']} />
        <mesh geometry={nodes.BezierCurve001_1.geometry} material={materials.silver} />
      </group>
      <mesh geometry={nodes.Cap.geometry} material={materials.silver} position={[0, 32.655, 0]} scale={6.127} />
      <mesh geometry={nodes.opener.geometry} material={materials.silver} position={[-0.004, 32.744, -1.587]} rotation={[0.08, 0, 0]} scale={0.207} />
    </group>
  )
}

useGLTF.preload('/can1.glb')
